### PR TITLE
Europe

### PR DESCRIPTION
**Pull request by scivm**
EU data is taken from the following sources:

geonames.org - postal code data is taken from https://download.geonames.org/export/zip/
    License:  Creative Commons Attribution 3.0 License

openstreetmap.com - health site data is extracted from open street maps.
    License: Open Database License
    “© OpenStreetMap contributors”.  https://www.openstreetmap.org/copyright

Azure pipelines to generate data:
    https://github.com/science-automation/genSyntheaEU
    https://dev.azure.com/shambergerm/SyntheaInternational/_build

still needs work and more complete testing.  Government data sources are usually better so will replace individual country data sites if those are found.  Data can also be improved by users updating openstreetmap with hospital and clinic data.

### CODE REVIEW

**Comment by jawalonoski** [comment]
@scivm Wow. Thank you for this impressive pull request.

Have you tested each of these countries by at least making sure they successfully execute without errors?

Also, I've invited you to have permissions on this repository.

**Comment by scivm** [comment]
Hi,

I have only tested some regions in Spain and Great Britain.  Let me write a
script to check them all.  It will likely take a few days.   Open street
maps needs to have at least one hospital in the region with tag
emergency=Yes which gets mapped to urgent care.  So I have to add an entry
to openstreetmaps and run that script again if there is not at least one.

Thanks for giving the repo privileges.

Mike

**Comment by jawalonoski** [comment]
OK, I won't merge this PR until you have a chance to run your script and can report on the results. I'm not sure there is a great way to enable continuous integration on this repository without having a build that takes forever to test all the locations.

**Comment by scivm** [comment]
So far I have 170 of 602 passing this basic test:   Does region to be modeled exist in ['timezones','demographics','zipcodes','hospitals','urgent','primary'].  Issue is that zip code files are mostly ascii international name and hospital data contains european chars with local name.

**Comment by scivm** [comment]
Now 293 of 714 passing basic test.   Added back in some GB regions so total is higher now.  Likely I can fix a few more countries and then remove the ones that have 0 passing for first merge.

**Comment by scivm** [comment]
Now 350 of 646 passing basic test.   I noticed that any region (state) with european or cyrillic chars is not working when running.  Looking into that one.   For example, Cēsu Novads or Габрово

**Comment by jawalonoski** [comment]
@scivm Any progress here? Should I merge as-is?

**Comment by scivm** [comment]
Hi.

Will check it out again.  It was real close to ready before corona hit.

Mike

**Comment by scivm** [comment]
353/515 passing now.  I think it could be merged now.  I have provided a report on what regions are working and what are not.  Over time, the percentage can be increased and new countries added.

**Comment by jawalonoski** [comment]
Great. Thanks for all the effort. Deeply appreciated.

**Pull request merged**
