### PR TITLE
Canada

### PR DESCRIPTION
**Pull request by jawalonoski**
This pull request adds configuration files for Canada.

Data was sourced from Statistics Canada websites, specifically:

- 2016 Census Data (https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/prof/details/download-telecharger/comp/GetFile.cfm?Lang=E&FILETYPE=CSV&GEONO=044)
- Open Database of Healthcare Facilities (https://www.statcan.gc.ca/eng/lode/databases/odhf).

The timezone data, zip/postal codes, and latitude/longitude data are functional, but should be viewed with suspicion (i.e. there are inaccuracies).

Thanks to @pooky1955, @mnqng, and @jakatut for spurring the creation this Pull Request. See https://github.com/synthetichealth/synthea/issues/781

### CODE REVIEW

**Comment by pooky1955** [comment]
Is there a reason as to why this pull request is still open? Is there any way I can help?

**Comment by jawalonoski** [comment]
> Is there a reason as to why this pull request is still open? Is there any way I can help?

I'm waiting for someone else to test it successfully before merging it in, in case I missed something.

**Comment by jawalonoski** [comment]
Someone tested it. I need to fix some facility IDs.

**Comment by jawalonoski** [comment]
Comments from a user that this change deconflicted some facility IDs was successful.

**Comment by pooky1955** [comment]
Thank you very much!

**Comment by pmedvedev** [comment]
@jawalonoski apologies for the post on an old thread. I'm new to using Synthea. Trying my hand at generating some sample data but running into issues with the Canadian package. Looking for some guidance to documentation or general troubleshooting. I've cloned both main repo and international repo to my machine. I've ran "./gradlew build check test" and successfully created a patient with the standard US data. As a next step, I've followed the Readme guidance from the international package:

```
git clone https://github.com/synthetichealth/synthea
git clone https://github.com/synthetichealth/synthea-international
cd synthea-international
cp -R ca/* ../synthea
cd ../synthea
./run_synthea -p 5 Alberta
```
However, that did not work. I then assumed I need to rerun "./gradlew build check test", but unfortunately that also seemed to have failed and based on what I gathered from the logs, something to do with not having all of the "ca" variants configured in properties. 

Appreciate any help/guidance in advance.

**Pull request merged**
